[YDBTest#908] Fixed %YDB-W-MUNOTALLSEC messages in case of go/unit_tests subtest failure
Background
----------

Previously, the `go/unit_tests` subtest would occasionally fail with the following diff:

```diff
2c2
< PASS from unit_tests
---
> FAIL from unit_tests. Please check unit_tests/unit_tests.diff and unit_tests/errs_found.logx for errors in time sorted fashion
--------- Subtest level diff follows ---------

unit_tests took 00:00:00:26 from 2026.04.10.20.08.05.EDT to 2026.04.10.20.08.31.EDT : 11888 FAIL
--- unit_tests/unit_tests.diff ---
5c5,21
< PASS
---
> TEST-E-FAILED : [go test -C YDBGo/v2 -buildvcs=false -asan] failed for v2:
> go: downloading lang.yottadb.com/go/yottadb v1.2.8
> --- FAIL: TestLock (0.26s)
>     conn_test.go:151:
>             Error Trace: TEST_DIR/YDBGo/v2/conn_test.go:151
>             Error:        Not equal:
>                           expected: false
>                           actual  : true
>             Test:         TestLock
> FAIL
> exit status 1
> FAIL lang.yottadb.com/go/yottadb/v2      3.758s
> TEST_DIR/leftover_ipc_cleanup_if_needed.out
> %YDB-W-MUNOTALLSEC, WARNING: not all global sections accessed were successfully rundown
> CHECK-W-SEM : 655098085 is not expected to be left around. (debug info :  dbfile=mumps.dat --> sem=655098085,shm=778666114,ftoksem=0x2bb93d92 )
> CHECK-W-SEM : 0x2bb93d92 is not expected to be left around. (debug info :  dbfile=mumps.dat --> sem=655098085,shm=778666114,ftoksem=0x2bb93d92 )
> CHECK-W-SHM : 778666114 is not expected to be left around. (debug info :  dbfile=mumps.dat --> sem=655098085,shm=778666114,ftoksem=0x2bb93d92 )
```

Issue
-----

The `%YDB-W-MUNOTALLSEC` warnings occurred as a result of the underlying failure at `conn_test.go:151` and are otherwise unrelated to the failure. However, these warnings occurred due to a bug in the code, such that in the case of the above failure, the test would exit without waiting for child processes to complete, thus leaving open semaphores and shared memory segments.

Per the discussions at https://gitlab.com/YottaDB/Lang/YDBGo/-/merge_requests/269#note_3258121243 and https://gitlab.com/YottaDB/Lang/YDBGo/-/merge_requests/269#note_3262800658, the underlying failure is due to test timing issue that can occur in rare cases due to YottaDB's lock `fairness` logic.

See also: https://gitlab.com/YottaDB/Lang/YDBGo/-/merge_requests/269#note_3255845561.

Fix
---

This commit fixes the timing issue by revising the `%XCMD` call in the spawned `yottadb` process in `v2/conn_test.go` to use a simple locking scheme instead of `hang 3` to remove the possibility of timing-related lock contention and reduce overall test runtime.

Additionally, `v2/Makefile` was updated to bump the test timeout from 5 to 20 seconds to prevent pipeline failures in case both locks in the above locking scheme come close to timing out (each has a 10-second timeout).