Add output to help diagnose rare TestLock failure in pipeline
An example failure at https://gitlab.com/berwynhoyt/YDBTest/-/jobs/12751190735
provides the following output.

```
> TEST-E-FAILED : [go test -C YDBGo/v2 -buildvcs=false -race] failed for v2:
> go: downloading lang.yottadb.com/go/yottadb v1.2.8
> --- FAIL: TestLock (0.03s)
> panic: exit status 154 [recovered]
> 	panic: exit status 154
>
> goroutine 99 [running]:
> testing.tRunner.func1.2({0x800780, 0xc0000d6780})
> 	/usr/lib/go-1.24/src/testing/testing.go:1734 +0x3eb
> testing.tRunner.func1()
> 	/usr/lib/go-1.24/src/testing/testing.go:1737 +0x696
> panic({0x800780?, 0xc0000d6780?})
> 	/usr/lib/go-1.24/src/runtime/panic.go:792 +0x132
> lang.yottadb.com/go/yottadb/v2.lockExists({0xc000180060, 0x16})
> 	/builds/berwynhoyt/YDBTest/testarea1/tst_V999_R999_dbg_01_260117_035629_A9r/go_0/unit_tests/YDBGo/v2/conn_test.go:163 +0x2f8
> lang.yottadb.com/go/yottadb/v2.TestLock(0xc000185340)
> 	/builds/berwynhoyt/YDBTest/testarea1/tst_V999_R999_dbg_01_260117_035629_A9r/go_0/unit_tests/YDBGo/v2/conn_test.go:110 +0x265
> testing.tRunner(0xc000185340, 0x82e990)
> 	/usr/lib/go-1.24/src/testing/testing.go:1792 +0x226
> created by testing.(*T).Run in goroutine 1
> 	/usr/lib/go-1.24/src/testing/testing.go:1851 +0x8f3
> exit status 2
> FAIL	lang.yottadb.com/go/yottadb/v2	3.198s
```

Also did some minor maintenance:
 - removed unused and incompletely implemented `go test` flag `-nodb` in favor of flag `-testdb=` which already does what is needed.
 - moved `go test` flag `noinit` source from init_test.go to where all the other test flags are defined in yottadb_test.go.